name: 🎨 フロントエンド
description: フロントエンド(Next.js/React)に関するissue
title: "[Frontend] "
labels: ["frontend"]
body:
  - type: markdown
    attributes:
      value: |
        フロントエンドに関するissueを報告してください。
      
  - type: textarea
    id: description
    attributes:
      label: 説明
      description: issueの詳細を記載してください
      placeholder: |
        何が起きているのか、何を実装したいのかを具体的に記述してください。
    validations:
      required: false
