inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"
    - "aws/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/**/*"
    - "config/puma.rb"
    - "test/**/*"

### ルールのカスタマイズ

# 設定が厳しいので一旦全てfalseにする
Metrics:
  Enabled: false


# 一行あたりの文字数
Layout/LineLength:
  Enabled: false

# メソッドの改行ルール
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EndOfLine:
  EnforcedStyle: lf


# 日本語にコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスにコメントを残さなくても良い
Style/Documentation:
  Enabled: false

# コントローラ等のモジュールをネストしての宣言
Style/ClassAndModuleChildren:
  Enabled: false

# 文字列のfreeze（Ruby3からは自動でfreezeされるので要らない）
Style/FrozenStringLiteralComment:
  Enabled: false

# ガード節の提案（難しいので一旦false）
Style/GuardClause:
  Enabled: false

# 文字列のダブルクォートチェック
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AndOr:
  Enabled: true

# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Enabled: false
  # EnforcedStyle: brackets

# 文字列による配列の%記法のチェック
Style/WordArray:
  Enabled: false


# 変数名に数字を許可
Naming/VariableNumber:
  Enabled: false

# 命名に英語以外を禁止
Naming/AsciiIdentifiers:
  Enabled: true

# クラスとモジュールの命名をキャメルケースに
Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/MethodName:
  Enabled: true
  # メソッド名はsnake_caseに
  EnforcedStyle: snake_case

Naming/VariableName:
  Enabled: true
  # 変数名はsnake_caseに
  EnforcedStyle: snake_case

# 定数はSCREAMING_SNAKE_CASEに
Naming/ConstantName:
  Enabled: true

# ファイル名はsnake_caseに
Naming/FileName:
  Enabled: true


Lint/UselessAssignment:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

# = と == の指摘
Lint/AssignmentInCondition:
  Enabled: false


# 未i18nのチェック（バリデーションエラーメッセージをi18nに登録するのはやや冗長？なためfalse）
Rails/I18nLocaleTexts:
  Enabled: false

# before_actionの際の未定義メソッドのチェック（deviseとの兼ね合いで一旦false）
Rails/LexicallyScopedActionFilter:
  Enabled: false
