services:
  db:
    image: postgres:16.10-alpine3.22
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle install && bin/dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/srv:cached
      - bundle_ruby:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      DATABASE_USER: root
      DB_HOST: db
      DB_NAME: nari_note_backend_development

volumes:
  postgres:
  bundle_ruby:
