source "https://rubygems.org"

gem "rails", "~> 8.0.3"
gem "puma", ">= 5.0"

# util
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Database
gem "activerecord-import"
gem "activerecord-simple_index_name"
gem "pg", "~> 1.1"
gem "solid_cache"

# Launch
gem "bootsnap", require: false

group :development, :test do
  gem "brakeman", require: false
  gem "pry", require: false
  gem "pry-byebug", require: false
  gem "pry-rails", require: false
end

group :development do
  gem "annotaterb", require: false
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rails-omakase", require: false
end
